from wpimath.units import radians


class Intake:
    def setup(self) -> None: ...

    def set_arm_voltage(self, voltage: float) -> None: ...

    def set_wheel_voltage(self, voltage: float) -> None: ...

    def execute(self) -> None: ...
