import math

from phoenix6 import CANBus
from phoenix6.hardware import TalonFX, TalonFXS

from wpimath import units

import oi

from components.drive_control import DriveControl
from components.shooter import Shooter
from components.swerve_drive import SwerveDrive
from components.game_piece_sim import GamePieceSim

from generated.tuner_constants import TunerConstants

from lemonlib import LemonInput, LemonRobot
from lemonlib.smart import SmartPreference, SmartProfile
from lemonlib.util import (
    AlertManager,
    AlertType,
    curve,
)


class MyRobot(LemonRobot):

    # TODO: Score controller: highest level component that uses shooter controller to shoot and swerve to aim and only shoots when it should
    # TODO: Shooter controller: uses shooter component to shoot and indexer
    drive_control: DriveControl
    shooter: Shooter
    # TODO: Indexer component
    game_piece_sim: GamePieceSim

    drivetrain: SwerveDrive
    # TODO: Intake component
    # TODO: LED component

    # Greatest speed that chassis should move (not greatest possible speed)
    top_speed = SmartPreference(4.7)
    top_omega = SmartPreference(6.0)

    def createObjects(self):
        """
        - It puts all of your motor/sensor initialization in the same
          place, so that if you need to change a port/pin number it
          makes it really easy to find it. Additionally, if you want
          to create a simplified robot program to test a specific
          thing, it makes it really easy to copy/paste it elsewhere

        - It allows you to use the magic injection mechanism to share
          variables between components
        """

        """
        SWERVE (Note most stuff is in tuner constrants generated by phoenix tuner)
        """

        self.max_speed: units.meters_per_second = TunerConstants.speed_at_12_volts

        self.translation_profile = SmartProfile(
            "translation",
            {
                "kP": 5.0,
                "kI": 0.0,
                "kD": 0.0,
            },
            (not self.low_bandwidth),
        )
        self.rotation_profile = SmartProfile(
            "rotation",
            {
                "kP": 7.0,
                "kI": 0.0,
                "kD": 0.1,
                "kMaxV": 8.0,
                "kMaxA": 40.0,
                "kMinInput": -math.pi,
                "kMaxInput": math.pi,
            },
            (not self.low_bandwidth),
        )

        """
        INTAKE
        """

        self.intake_canbus = CANBus.system_core(1)

        self.intake_spin_motor = TalonFX(51, self.intake_canbus)
        self.intake_left_motor = TalonFXS(52, self.intake_canbus)
        self.intake_right_motor = TalonFXS(53, self.intake_canbus)

        self.intake_spin_amps: units.amperes = 60.0
        self.intake_arm_amps: units.amperes = 24.0

        """
        SHOOTER
        """

        self.shooter_canbus = CANBus.system_core(0)

        self.shooter_left_motor = TalonFX(2, self.shooter_canbus)
        self.shooter_right_motor = TalonFX(3, self.shooter_canbus)

        self.shooter_gear_ratio = 1.6
        self.shooter_stator_amps: units.amperes = 120.0
        self.shooter_supply_amps: units.amperes = 70.0
        self.shooter_peak_amps: units.amperes = 140.0

        self.shooter_angle = 23  # degrees

        self.shooter_profile = SmartProfile(
            "shooter",
            {
                "kP": 0.35,
                "kI": 0.0,
                "kD": 0.0,
                "kS": 0.075,
                "kV": 0.179,
                "kA": 0.13,  # 0.29663,
            },
            (not self.low_bandwidth),
        )

        """
        INDEXER
        """
        self.indexer_canbus = CANBus.system_core(2)

        self.indexer_left_kicker_motor = TalonFXS(4, self.shooter_canbus)
        self.indexer_right_kicker_motor = TalonFXS(5, self.shooter_canbus)
        self.indexer_conveyor_motor = TalonFXS(6, self.indexer_canbus)
        self.indexer_kicker_amps: units.amperes = 40.0
        self.indexer_conveyor_amps: units.amperes = 20.0

        """
        MISCELLANEOUS
        """

        # driving curve
        self.sammi_curve = curve(
            lambda x: 1.89 * x**3 + 0.61 * x,
            0.0,
            deadband=0.1,
            max_mag=1.0,  # This just makes a cubic curve for drive the bot with joysticks with deadband
        )

        # alerts
        AlertManager(self.logger)
        if self.low_bandwidth:
            AlertManager.instant_alert(
                "Low Bandwidth Mode is active! Tuning is disabled.", AlertType.INFO
            )

    """
    MODE INITIALIZATION
    """

    def teleopInit(self) -> None:
        self.primary = LemonInput(0)
        self.secondary = LemonInput(1)
        self.oi = oi.DoubleOI(self.primary, self.secondary)

    """
    PERIODIC
    """

    def teleopPeriodic(self) -> None:
        """
        SWERVE
        """

        self.drive_control.request_drive_field(
            self.sammi_curve(self.oi.drive_forward()) * self.top_speed,
            self.sammi_curve(self.oi.drive_strafe()) * self.top_speed,
            self.sammi_curve(self.oi.drive_rotation()) * self.top_omega,
        )

        """
        SHOOTER
        """
        if self.oi.hard_shoot():
            self.shooter.set_velocity(47.5)
