import math

import phoenix6
from phoenix6 import CANBus, SignalLogger, units
from phoenix6.hardware import TalonFX, TalonFXS
from wpilib import DutyCycleEncoder, Gamepad, Notifier, RobotController
from wpimath import Rotation2d

import oi
from components.indexer import Indexer
from components.intake import Intake, Intake_Angle
from components.kicker import Kicker
from components.leds import LEDStrip
from components.shooter import Shooter
from components.swerve_drive import SwerveDrive
from components.simulation.swerve_sim import SwerveSim
from components.simulation.intake_sim import IntakeSim
from controllers.ballistics import Ballistics
from controllers.drive_control import DriveControl
from controllers.game_piece_sim import GamePieceSim
from controllers.score_controller import ScoreController
from controllers.shooter_controller import ShooterController
from generated.tuner_constants import TunerConstants
from lemonlib import LemonRobot
from lemonlib.smart import SmartPreference, SmartProfile
from lemonlib.util import (
    AlertManager,
    AlertType,
    curve,
)


class MyRobot(LemonRobot):
    score_controller: ScoreController
    ballistics: Ballistics
    shooter_controller: ShooterController
    drive_control: DriveControl

    drivetrain: SwerveDrive
    intake: Intake
    shooter: Shooter
    indexer: Indexer
    kicker: Kicker
    leds: LEDStrip

    # Greatest speed that chassis should move (not greatest possible speed)
    top_speed = SmartPreference(4.7)
    top_omega = SmartPreference(6.0)

    _SIM_LOOP_PERIOD: phoenix6.units.second = 0.004  # 4 ms temp

    def createObjects(self):
        """
        - It puts all of your motor/sensor initialization in the same
          place, so that if you need to change a port/pin number it
          makes it really easy to find it. Additionally, if you want
          to create a simplified robot program to test a specific
          thing, it makes it really easy to copy/paste it elsewhere

        - It allows you to use the magic injection mechanism to share
          variables between components
        """

        """
        SWERVE (Note most stuff is in tuner constrants generated by phoenix tuner)
        """

        SignalLogger.start()

        self.max_speed: units.meters_per_second = TunerConstants.speed_at_12_volts

        self.translation_profile = SmartProfile(
            "translation",
            {
                "kP": 5.0,
                "kI": 0.0,
                "kD": 0.0,
            },
            (not self.low_bandwidth),
        )
        self.rotation_profile = SmartProfile(
            "rotation",
            {
                "kP": 7.0,
                "kI": 0.0,
                "kD": 0.1,
                "kMaxV": 8.0,
                "kMaxA": 40.0,
                "kMinInput": -math.pi,
                "kMaxInput": math.pi,
            },
            (not self.low_bandwidth),
        )

        """
        INTAKE
        """

        self.intake_canbus = CANBus.systemcore(1)

        self.intake_spin_motor = TalonFX(51, self.intake_canbus)
        self.intake_left_motor = TalonFXS(52, self.intake_canbus)
        self.intake_right_motor = TalonFXS(53, self.intake_canbus)

        self.intake_encoder = DutyCycleEncoder(1)

        self.intake_spin_amps: units.ampere = 80.0
        self.intake_arm_amps: units.ampere = 40.0

        self.intake_profile = SmartProfile(
            "Intake",
            {
                "kP": 5.0,
                "kI": 0.0,
                "kD": 0.0,
                "kS": 0.0,
                "kV": 0.0,
                "kG": 0.0,
            },
            not self.low_bandwidth,
        )

        self.intake_tolerance = 3.0

        """
        SHOOTER
        """

        self.shooter_canbus = CANBus.systemcore(0)

        self.shooter_left_motor = TalonFX(2, self.shooter_canbus)
        self.shooter_right_motor = TalonFX(3, self.shooter_canbus)

        self.shooter_gear_ratio = 1.6
        self.shooter_stator_amps: units.ampere = 120.0
        self.shooter_supply_amps: units.ampere = 70.0
        self.shooter_peak_amps: units.ampere = 140.0

        self.shooter_angle = 23  # degrees

        self.shooter_profile = SmartProfile(
            "shooter",
            {
                "kP": 0.35,
                "kI": 0.0,
                "kD": 0.0,
                "kS": 0.075,
                "kV": 0.179,
                "kA": 0.13,  # 0.29663,
            },
            (not self.low_bandwidth),
        )

        """
        INDEXER
        """
        self.indexer_canbus = CANBus.systemcore(2)

        self.indexer_conveyor_motor = TalonFXS(6, self.indexer_canbus)
        self.indexer_conveyor_amps: units.ampere = 20.0

        """
        KICKER
        """
        self.kicker_left_motor = TalonFXS(4, self.shooter_canbus)
        self.kicker_right_motor = TalonFXS(5, self.shooter_canbus)
        self.kicker_amps: units.ampere = 40.0

        """
        MISCELLANEOUS
        """

        # driving curve
        self.sammi_curve = curve(
            lambda x: 1.89 * x**3 + 0.61 * x,
            0.0,
            deadband=0.1,
            max_mag=1.0,  # This just makes a cubic curve for drive the bot with joysticks with deadband
        )

        # alerts
        AlertManager(self.logger)
        if self.low_bandwidth:
            AlertManager.instant_alert(
                "Low Bandwidth Mode is active! Tuning is disabled.", AlertType.INFO
            )

    """
    MODE INITIALIZATION
    """

    def teleopInit(self) -> None:
        self.primary = Gamepad(0)
        self.secondary = Gamepad(1)
        # self.oi = oi.Twitch_OI()
        # self.oi = oi.DoubleOI(self.primary, self.secondary)
        self.oi = oi.SingleOI(self.primary)

    def _simulationInit(self):
        self.swerve_sim = SwerveSim(
            self.drivetrain
        )  # Has a notifier built in so does not need periodic called

        self.intake_sim = IntakeSim(self.intake)

    def _simulationPeriodic(self) -> None:
        self.intake_sim.simulation_periodic()

    """
    PERIODIC
    """

    def teleopPeriodic(self) -> None:
        """
        SWERVE
        """
        with self.consumeExceptions():
            # if both 25% else 50 or 75
            if self.oi.drive_limit_speed50() and self.oi.drive_limit_speed75():
                mult = 0.25
            elif self.oi.drive_limit_speed75():
                mult = 0.75
            elif self.oi.drive_limit_speed50():
                mult = 0.5
            else:
                mult = 1.0

            self.drive_control.request_drive_field(
                self.sammi_curve(self.oi.drive_forward()) * self.top_speed * mult,
                self.sammi_curve(self.oi.drive_strafe()) * self.top_speed * mult,
                self.sammi_curve(self.oi.drive_rotation()) * self.top_omega * mult,
            )
            if self.oi.reset_gyro():
                self.drivetrain.reset_heading()

        """
        SHOOTER
        """
        with self.consumeExceptions():
            if self.oi.hard_shoot():
                self.shooter_controller.request_shot(47.5)
            elif self.oi.auto_shoot():
                self.score_controller.request_score()
            elif self.oi.unjam():
                self.shooter.set_voltage(-8.0)
                self.kicker.set_voltage(-8.0)

        """
        INTAKE
        """
        with self.consumeExceptions():
            if self.oi.intake():
                self.intake.set_spin_throttle(0.8)
            elif self.oi.outtake():
                self.intake.set_spin_throttle(-0.8)

            if self.oi.intake_up():
                self.intake.set_arm_voltage(-10.0)
                # self.intake.set_arm_angle(Intake_Angle.STOWED)
            elif self.oi.intake_down():
                self.intake.set_arm_voltage(6.0)
                # self.intake.set_arm_angle(Intake_Angle.DOWN)
